// Intensities
export const DEFAULT_GRADIENT_COLOR_INTENSITY = 5;
export const DEFAULT_SCANNING_CIRCLE_INTENSITY = 5;
export const DEFAULT_SCANNING_LINE_INTENSITY = 10;
// Speeds
export const DEFAULT_SCANNING_CIRCLE_SPEED = 200;
export const DEFAULT_SCANNING_LINE_SPEED = 50;
// Width
export const DEFAULT_SCANNING_CIRCLE_WIDTH = 10;
